/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rnaneobjtzdhtsyomjid"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuYW5lb2JqdHpkaHRzeW9tamlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NDQwMjksImV4cCI6MjA5MTMyMDAyOX0.9M_h3ZeaIAYzw-_MxjIQ-b0p65YebJi00iGtdCVZ1c8"